---
title: "extracting arguments from a function"
author: "Charles T. Gray"
date: "14/05/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
# packages

library(tidyverse)
library(knitr)

```

```{r how r works}

# test if names preserves the order
list(c = 2, a = 3) %>% names()




```


```{r defaults}

# how to get 

get_defaults <- function(a = 1, b = letters[3:6]){
  formals() %>% {
    tibble(
      argument = names(.),
      value = as.list(.)
    )
  } 
  
}


# check defaults
get_defaults() 

# does it still return defaults?
get_defaults(a = 3) 


```


```{r specified}



get_specified <- function(a = 1, b = letters[3, 6]) {
  output <- match.call()
  
  if (!is.null(output %>% names())) {
    as.list(output)[-1] %>%  {
      tibble(argument = names(.),
             value = as.list(.))
      
    }
  } else {
    "no specified args"
  }}



get_specified() %>% kable()

get_specified(a = 3) %>% kable()

get_specified(a = 3, b = "hello, world") %>% kable()



```


```{r}



```


```{r}
# put them together






get_arguments <- function(a = 3, b = letters[1:3], ...) {
  match_call <- match.call()
  names_match_call <- names(match_call)
  
  specified_args <- if (!is.null(names_match_call)) {
    as.list(match_call)[-1] %>%  {
      tibble(argument = names(.),
             specified = as.list(.))
      
    }
  } else {
    "no specified args"
  }
  
  defaults <- formals() %>% {
    tibble(argument = names(.),
           default = as.list(.)) # %>% mutate(value = map(value, 1))
    }
  
  
  output <- if (!is.character(specified_args)) {
    defaults %>% 
      full_join(specified_args, by = "argument") %>% 
        mutate(default_flag = map_lgl(specified, is.null),
         value = if_else(
           default_flag,
           default,
           specified
         )) %>% 
  arrange(argument)
 
  } else {defaults}

  return(output)
}

get_arguments()

get_arguments(a = 3, x = "1")
 
```


```{r}


get_arguments(a = 3, x = "1") %>% 


```

