---
title: "metasim loop"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, message=FALSE}
library(tidyverse)
library(metasim)
```


```{r include=FALSE}
# set.seed(38)

results_df <- metasims()

```

```{r}

results_df %>% group_by(effect_type) %>% skimr::skim()
```



```{r}
results_df %>% 
  ggplot(aes(x = rdist, y = cp)) +
  geom_point(position = "jitter", aes(colour = bias))

```

```{r}
results_df %>% 
  filter(effect_type != "md") %>% 
  ggplot(aes(x = bias, y = cp)) +
  geom_point(alpha = 0.4, aes(colour = rdist)) +
  facet_grid(median_ratio ~ effect_type)

```

```{r eval=FALSE}
results_df %>% 
  filter(effect_type != "md", 
           rdist == "pareto") %>% 
  ggplot(aes(x = parameters, y = cp)) +
  geom_hline(yintercept = 0.95, linetype = "dashed") +
  geom_point(aes(size = bias, 
                 colour = ci_width,
                 shape = effect_type, 
                 alpha = 0.4), position = "jitter") +
  theme(text = element_text(angle = 60)) +
  facet_grid(k ~ between_study_variation) 


```
]
